name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # تغيير الفرع إذا كان مختلفًا

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # أي أوامر لبناء الموقع (مثل `npm run build` لـ React)
          echo "Building the site..."
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # تغيير المسار إذا كان مختلفًا
